# Generated by Django 4.1.1 on 2022-11-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0022_alter_discapacidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_alimentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 1 de formulario')),
                ('pregunta2', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 2 de formulario')),
                ('pregunta3', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 3 de formulario')),
                ('pregunta4', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 4 de formulario')),
                ('pregunta5', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 5 de formulario')),
                ('pregunta6', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 6 de formulario')),
                ('pregunta7', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 7 de formulario')),
                ('pregunta8', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 8 de formulario')),
                ('pregunta9', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 9 de formulario')),
                ('pregunta10', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Pregunta 10 de formulario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estudiante')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
                'ordering': ['pregunta1'],
            },
        ),
    ]
