# Generated by Django 4.1.1 on 2022-11-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0015_calificacion'),
        ('formularios', '0002_formulario_alimentario_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario_alimentario',
            options={'ordering': ['ficha'], 'verbose_name': 'formulario', 'verbose_name_plural': 'formularios'},
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta1',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta10',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta2',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta3',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta4',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta5',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta6',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta7',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta8',
        ),
        migrations.RemoveField(
            model_name='formulario_alimentario',
            name='pregunta9',
        ),
        migrations.AddField(
            model_name='formulario_alimentario',
            name='alimento',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Nombre alimento'),
        ),
        migrations.AddField(
            model_name='formulario_alimentario',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de consumo'),
        ),
        migrations.AddField(
            model_name='formulario_alimentario',
            name='comentario',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Comentario del nutricionista'),
        ),
        migrations.AddField(
            model_name='formulario_alimentario',
            name='ficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutricion.detalle_atencion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario_alimentario',
            name='frecuencia',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Frecuencia de consumo alimento'),
        ),
    ]
