# Generated by Django 4.1.1 on 2022-11-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_alter_disciplina_options'),
        ('formularios', '0003_alter_formulario_alimentario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_satisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaccion', models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Satisfaccion')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.estudiante')),
            ],
            options={
                'verbose_name': 'satisfaccion',
                'verbose_name_plural': 'satisfacciones',
                'ordering': ['estudiante'],
            },
        ),
    ]
