# Generated by Django 4.1.1 on 2022-10-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, default='activo', max_length=100, null=True, verbose_name='Estado solicitud')),
                ('atencion_1', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación atencion 1')),
                ('atencion_2', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación atencion 2')),
                ('atencion_3', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación atencion 3')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación solicitud ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['user'],
            },
        ),
    ]
