# Generated by Django 4.1.1 on 2022-10-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100, verbose_name='Nombre paciente')),
                ('genero', models.CharField(max_length=15, verbose_name='orientación sexual')),
                ('fecha_nac', models.DateField(verbose_name='Fecha nacimiento paciente')),
                ('fecha_eval', models.DateTimeField(auto_now_add=True, verbose_name='Fecha atencion')),
                ('edad', models.IntegerField(verbose_name='Fecha atencion')),
                ('estatura', models.FloatField(blank=True, null=True)),
                ('peso_prom', models.FloatField(blank=True, null=True)),
                ('peso_circunferencia_cin', models.FloatField(blank=True, null=True)),
                ('peso_circunferencia_braq', models.FloatField(blank=True, null=True)),
                ('prom_pliegue_t', models.IntegerField(verbose_name='promedio pliegue triciptal')),
                ('prom_pliegue_b', models.IntegerField(verbose_name='promedio pliegue biciptal')),
                ('prom_pliegue_se', models.IntegerField(verbose_name='promedio pliegue subescapular')),
                ('prom_pliegue_si', models.IntegerField(verbose_name='promedio pliegue suprailiaco')),
                ('sum_pliegues', models.IntegerField(verbose_name='suma todos los pliegues')),
                ('porc_grasa', models.FloatField(blank=True, null=True, verbose_name='procentaje de grasa')),
                ('diag_nutri', models.CharField(max_length=1500, verbose_name='comentario')),
                ('prom_pliegue_abd', models.IntegerField(blank=True, default=None, null=True, verbose_name='promedio pliegue abdominal')),
                ('prom_pliegue_pant', models.IntegerField(blank=True, default=None, null=True, verbose_name='promedio pliegue pantorilla')),
                ('prom_pliegue_media', models.IntegerField(blank=True, default=None, null=True, verbose_name='promedio pliegue media')),
                ('prom_pliegue_supra', models.IntegerField(blank=True, default=None, null=True, verbose_name='promedio pliegue supraespinal')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutricion.solicitud')),
            ],
            options={
                'verbose_name': 'Detalle_atencion',
                'verbose_name_plural': 'Detalles_atenciones',
                'ordering': ['nombre_paciente'],
            },
        ),
    ]
