# Generated by Django 4.1.1 on 2022-10-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_detalle_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_atencion',
            name='estatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='peso_circunferencia_braq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='peso_circunferencia_cin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='peso_prom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='porc_grasa',
            field=models.FloatField(verbose_name='procentaje de grasa'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación solicitud'),
        ),
    ]
