# Generated by Django 4.1.1 on 2022-10-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_alter_detalle_atencion_estatura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_atencion',
            old_name='peso_circunferencia_braq',
            new_name='prom_circunferencia_braq',
        ),
        migrations.RenameField(
            model_name='detalle_atencion',
            old_name='peso_circunferencia_cin',
            new_name='prom_circunferencia_cin',
        ),
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='solicitud',
        ),
    ]
