# Generated by Django 4.1.1 on 2022-10-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_rename_fecha_naciemiento_paciente_fecha_nacimiento'),
        ('nutricion', '0004_rename_peso_circunferencia_braq_detalle_atencion_prom_circunferencia_braq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_atencion',
            options={'verbose_name': 'Detalle_atencion', 'verbose_name_plural': 'Detalles_atenciones'},
        ),
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='fecha_nac',
        ),
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='nombre_paciente',
        ),
        migrations.AddField(
            model_name='detalle_atencion',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.paciente'),
        ),
    ]
