# Generated by Django 4.1.1 on 2022-10-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_alter_detalle_atencion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_abd',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='promedio pliegue abdominal'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_b',
            field=models.FloatField(verbose_name='promedio pliegue biciptal'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_media',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='promedio pliegue media'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_pant',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='promedio pliegue pantorilla'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_se',
            field=models.FloatField(verbose_name='promedio pliegue subescapular'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_si',
            field=models.FloatField(verbose_name='promedio pliegue suprailiaco'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_supra',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='promedio pliegue supraespinal'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='prom_pliegue_t',
            field=models.FloatField(verbose_name='promedio pliegue triciptal'),
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='sum_pliegues',
            field=models.FloatField(verbose_name='suma todos los pliegues'),
        ),
    ]
