# Generated by Django 4.1.1 on 2022-10-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_paciente_genero'),
        ('nutricion', '0007_alter_detalle_atencion_estatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_atencion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.estudiante'),
        ),
    ]
