# Generated by Django 4.1.1 on 2022-10-25 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutricion', '0010_alter_solicitud_fecha_eval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
