# Generated by Django 4.1.1 on 2022-10-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0011_alter_solicitud_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_add',
            field=models.DateField(auto_now_add=True, default='2022-10-28', verbose_name='Fecha creacion'),
            preserve_default=False,
        ),
    ]
