# Generated by Django 4.1.1 on 2022-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0012_solicitud_fecha_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_atencion',
            name='recomendacion',
            field=models.CharField(blank=True, default='None', max_length=1500, null=True, verbose_name='Recomendación'),
        ),
    ]
