# Generated by Django 4.1.1 on 2022-11-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0013_detalle_atencion_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_atencion',
            name='recomendacion',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Recomendación'),
        ),
    ]
