# Generated by Django 4.1.1 on 2022-12-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0016_detalle_atencion_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_atencion',
            name='created',
        ),
        migrations.AlterField(
            model_name='detalle_atencion',
            name='fecha_eval',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha atencion'),
        ),
    ]
