# Generated by Django 4.1.1 on 2022-09-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre coordinador'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
