# Generated by Django 4.1.1 on 2022-09-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_profile_email_profile_nombre_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
