# Generated by Django 4.1.1 on 2022-10-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_profile_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nombre',
            new_name='name',
        ),
    ]
