# Generated by Django 4.1.1 on 2022-10-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_rename_nombre_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre coordinador')),
                ('rut', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='nombre coordinador')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='digito verificador coordinador')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, default='activo', max_length=100, null=True, verbose_name='Estado coordinador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre alumno')),
                ('rut', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='nombre alumno')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='digito verificador alumno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, default='activo', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('Profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.profesor')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'ordering': ['nombre'],
            },
        ),
    ]
