# Generated by Django 4.1.1 on 2022-10-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_alumno_rut_alter_profesor_dv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Profesor',
            new_name='profesor',
        ),
    ]
