# Generated by Django 4.1.1 on 2022-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_rename_profesor_alumno_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='rut'),
        ),
    ]
