# Generated by Django 4.1.1 on 2022-10-09 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0010_profile_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre profesor')),
                ('rut', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='rut profesor')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='digito verificador profesor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, default='activo', max_length=100, null=True, verbose_name='Estado profesor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre alumno')),
                ('rut', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='rut alumno')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='digito verificador alumno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, default='activo', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rut',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
