# Generated by Django 4.1.1 on 2022-10-11 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0012_alter_docente_dv_alter_docente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='activo', max_length=100, null=True, verbose_name='Nombre Paciente')),
                ('rut', models.CharField(blank=True, default='activo', max_length=8, null=True, unique=True, verbose_name='Rut paciente')),
                ('dv', models.CharField(blank=True, default='activo', max_length=1, null=True, verbose_name='Digito verificador Paciente')),
                ('fecha_naciemiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha nacimiento paciente')),
                ('disciplina', models.CharField(blank=True, default='activo', max_length=100, null=True, verbose_name='Disciplina paciente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email paciente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación paciente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
