# Generated by Django 4.1.1 on 2022-10-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinador',
            name='foto_perfil',
            field=models.ImageField(default='core/media/fotos_perfil/no-avatar.jpg', null=True, upload_to='fotos_perfil'),
        ),
    ]
