# Generated by Django 4.1.1 on 2022-10-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_remove_coordinador_foto_perfil_profile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(default='core/media/fotos_perfil/no-avatar.jpg', null=True, upload_to='core/static/core/media/fotos_perfil'),
        ),
    ]
