# Generated by Django 4.1.1 on 2022-10-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/no-avatar.jpg', null=True, upload_to='fotos_perfil'),
        ),
    ]
