# Generated by Django 4.1.1 on 2022-10-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Discapacidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disciplina paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Digito verificador Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_naciemiento',
            field=models.DateField(verbose_name='Fecha nacimiento paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Rut paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='discapacidades',
            field=models.ManyToManyField(related_name='discapacidad', to='registro.discapacidad'),
        ),
    ]
