# Generated by Django 4.1.1 on 2022-10-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_discapacidad_remove_paciente_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_naciemiento',
            new_name='fecha_nacimiento',
        ),
    ]
