# Generated by Django 4.1.1 on 2022-10-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_paciente_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discapacidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Discapacidad', 'verbose_name_plural': 'Discapacidades'},
        ),
    ]
