# Generated by Django 4.1.1 on 2022-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(default='no-avatar.jpg', null=True, upload_to='perfil'),
        ),
    ]
