# Generated by Django 4.1.1 on 2022-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_alter_coordinador_nombre_alter_docente_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplina',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='paciente',
            name='disciplina',
            field=models.ManyToManyField(related_name='disciplina', to='registro.disciplina'),
        ),
    ]
