# Generated by Django 4.1.1 on 2022-11-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0026_disciplina_remove_paciente_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nombre'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
    ]
